services:
  - type: web
    name: my-backend-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri-here
      - key: PORT
        value: 3000
    autoDeploy: true
    branch: main
