services:
  - type: web
    name: my-backend-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start.js
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://Carliest:Carlvalenciano25@cluster1.mq2hspb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
    autoDeploy: true